function [image] = pyramid2image(pyramid6)

%pyramid
%This function converts an image pyramid of 6 layers into a 256x256 image
%
%               [image] = pyramid2image(pyramid6)
%
%Input:
%   pyramid6: this is an image pyramid of 6 layers, which the biggest layer
%   is 256x256 and the smallest is 8x8
%
%Output:
%   image: this is a 256x256 double image generated by the pyramid

pfilt = '9/7';

image = lpr(pyramid6, pfilt);

end

